import { RegexPreset } from './types';

export const DEFAULT_PRESETS: RegexPreset[] = [
  {
    id: 'pii-redactor',
    name: 'PII Redactor',
    description: 'Finds and replaces emails, standard US phone numbers, and IPv4 addresses.',
    sampleText: 'Hi Alex, please send the invoice to finance-dept@example.net or support@globalcorp.org.\nFor urgent help, contact our hotline at +1 (800) 555-0199 or office phone (415) 555-2671.\nYour connection log shows IP addresses 192.168.1.15 and 10.0.0.128, please verify.',
    rules: [
      {
        id: 'email',
        pattern: '[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}',
        replacement: '[REDACTED_EMAIL]',
        flags: { global: true, caseInsensitive: true, multiline: false, dotAll: false },
        isActive: true,
        name: 'Email Addresses',
      },
      {
        id: 'phone',
        pattern: '\\b(?:\\+?1[-. ]?)?\\(?[2-9]\\d{2}\\)?[-. ]?\\d{3}[-. ]?\\d{4}\\b',
        replacement: '[REDACTED_PHONE]',
        flags: { global: true, caseInsensitive: false, multiline: false, dotAll: false },
        isActive: true,
        name: 'US Phone Numbers',
      },
      {
        id: 'ip-address',
        pattern: '\\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\b',
        replacement: '[REDACTED_IP]',
        flags: { global: true, caseInsensitive: false, multiline: false, dotAll: false },
        isActive: true,
        name: 'IPv4 Addresses',
      },
    ],
  },
  {
    id: 'html-stripper',
    name: 'HTML Tag Stripper',
    description: 'Removes HTML tags, inline styles, and javascript blocks.',
    sampleText: '<!DOCTYPE html>\n<html>\n<head>\n  <style>\n    body { font-family: sans-serif; }\n    h1 { color: #333; }\n  </style>\n</head>\n<body>\n  <header class="bg-blue-600">\n    <h1>Customer Report</h1>\n  </header>\n  <main>\n    <p>We saw an increase in throughput. <span style="font-weight: bold;">Verify all statistics.</span></p>\n  </main>\n  <script>\n    console.log("Telemetry reporting initiated...");\n    window.alert("Process complete!");\n  </script>\n</body>\n</html>',
    rules: [
      {
        id: 'script-tag',
        pattern: '<script\\b[^<]*(?:(?!<\\/script>)<[^<]*)*<\\/script>',
        replacement: '',
        flags: { global: true, caseInsensitive: true, multiline: false, dotAll: true },
        isActive: true,
        name: 'Script Blocks',
      },
      {
        id: 'style-tag',
        pattern: '<style\\b[^<]*(?:(?!<\\/style>)<[^<]*)*<\\/style>',
        replacement: '',
        flags: { global: true, caseInsensitive: true, multiline: false, dotAll: true },
        isActive: true,
        name: 'Style Blocks',
      },
      {
        id: 'html-tag',
        pattern: '<[^>]+>',
        replacement: '',
        flags: { global: true, caseInsensitive: false, multiline: false, dotAll: false },
        isActive: true,
        name: 'HTML tags',
      },
    ],
  },
  {
    id: 'whitespace-optimizer',
    name: 'Whitespace & Blank Lines',
    description: 'Trims spaces, collapses double spaces, and removes blank/empty lines.',
    sampleText: 'This is a sample document.   There are   too many spaces here.   \n\n\n\nWe also have a lot of empty blank lines above.  \n\n\nAnd some trailing spaces on this line.       \nLet us organize the layout neatly.  ',
    rules: [
      {
        id: 'excessive-newlines',
        pattern: '\\n{3,}',
        replacement: '\n\n',
        flags: { global: true, caseInsensitive: false, multiline: false, dotAll: false },
        isActive: true,
        name: 'Triple+ Newlines',
      },
      {
        id: 'double-spaces',
        pattern: '[ \\t]{2,}',
        replacement: ' ',
        flags: { global: true, caseInsensitive: false, multiline: true, dotAll: false },
        isActive: true,
        name: 'Double/Multiple Spaces',
      },
      {
        id: 'trailing-spaces',
        pattern: '[ \\t]+$',
        replacement: '',
        flags: { global: true, caseInsensitive: false, multiline: true, dotAll: false },
        isActive: true,
        name: 'Trailing Spaces on Lines',
      },
    ],
  },
  {
    id: 'markdown-cleaner',
    name: 'Markdown Stripper',
    description: 'Strips markdown elements such as code blocks, headers, links, and bold/italic indicators.',
    sampleText: '# Project Clean-up\n\nWelcome to our markdown documentation. This is **strongly recommended** for all teams.\nCheck out the [Live Demo](https://regex-cleaner.example.com) for real-time verification!\n\n## Implementation Details\n\nWe write files as follows:\n```typescript\nfunction log(msg: string) {\n  console.log("[LOG]", msg);\n}\n```\nLet\'s keep the logs *highly clean* and tidy.',
    rules: [
      {
        id: 'md-codeblock',
        pattern: '```[\\s\\S]*?```',
        replacement: '',
        flags: { global: true, caseInsensitive: false, multiline: false, dotAll: false },
        isActive: true,
        name: 'Markdown Code Blocks',
      },
      {
        id: 'md-link',
        pattern: '\\[([^\\]]+)\\]\\([^\\)]+\\)',
        replacement: '$1',
        flags: { global: true, caseInsensitive: false, multiline: false, dotAll: false },
        isActive: true,
        name: 'Links (keeps url text)',
      },
      {
        id: 'md-headers',
        pattern: '^\\s*#{1,6}\\s+',
        replacement: '',
        flags: { global: true, caseInsensitive: false, multiline: true, dotAll: false },
        isActive: true,
        name: 'Header Prefixes (#)',
      },
      {
        id: 'md-bold-italic',
        pattern: '[*_]{1,3}',
        replacement: '',
        flags: { global: true, caseInsensitive: false, multiline: false, dotAll: false },
        isActive: true,
        name: 'Bold / Italic markers (*, _)',
      },
    ],
  },
  {
    id: 'numbers-and-specials',
    name: 'Text Only',
    description: 'Leaves only basic alphabetic letters and spaces by stripping numbers and special punctuation symbols.',
    sampleText: 'In the year 2026, we grew our server network by 45%! (Our total cost was around $12,450.99 for 15 nodes... wow!).\nLet\'s filter out numbers, #hashtags, and punctuation to get only raw words.',
    rules: [
      {
        id: 'digits',
        pattern: '\\d+',
        replacement: '',
        flags: { global: true, caseInsensitive: false, multiline: false, dotAll: false },
        isActive: true,
        name: 'All Numbers/Digits',
      },
      {
        id: 'punctuation',
        pattern: '[\\!\\@\\#\\$\\%\\^\\&\\*\\(\\)\\-\\_\\+\\=\\[\\]\\{\\}\\;\\:\\\'\\"\\,\\.\\<\\>\\/\\?\\|\\\\\\`\\~]+',
        replacement: '',
        flags: { global: true, caseInsensitive: false, multiline: false, dotAll: false },
        isActive: true,
        name: 'Special Characters & Punctuation',
      },
    ],
  },
];
